Parameters:
  GitHubUser:
    Type: String
  GitHubRepo:
    Type: String

Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      RoleName: github-actions-role
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Ref GithubOidc
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub "repo:${GitHubUser}/${GitHubRepo}:*"
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
  GithubOidc:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - a031c46782e6e6c662c2c87c76da9aa62ccabd8e
        - 1b511abead59c6ce207077c0bf0e0043b1382612
Outputs:
  Role:
    Value: !GetAtt Role.Arn